#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Hook to run after EDITOR exits, following `git commit' $
#
############################################################ INFORMATION
#
# System requirements: awk(1) git(1)
# See also: .filters/fraubsd-keywords
#
############################################################ MAIN

DEBUG(){ [ ! "$DEBUG" ] || echo "DEBUG: $*"; }
DEBUG "$0 $*"

# Test the commit message file for content (indicating commit not aborted)
DEBUG "Checking commit message..."
awk '!/^[[:space:]]*(#|$)/{exit found++}END{exit !found}' "$1" &&
	{ DEBUG "Committing!"; exit 0; }
DEBUG "Commit aborted!"

# Commit aborted: Unset keywords in modified text-files
DEBUG "Keyword modifications..."
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -r0 .filters/fraubsd-keywords -d --
DEBUG "End List"

# Update the staging files
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -r0 git add -u -v --

################################################################################
# END
################################################################################
#
# $Copyright: 2015 The FrauBSD Project. All rights reserved. $
#
# $FrauBSD: .hooks/commit-msg 2015-11-14 21:56:06 -0800 freebsdfrau $
#
################################################################################
