#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Hook to run after a successful `git commit' $
#
############################################################ INFORMATION
#
# System requirements: git(1) ls(1)
# See also: .filters/gitfiles
#
############################################################ MAIN

DEBUG(){ [ ! "$DEBUG" ] || echo "DEBUG: $*"; }
DEBUG "$0 $*"

# Do a simple `ls -l' of recently committed files
DEBUG "Listing committed files..."
git show --name-only --format= | .filters/gitfiles ls -l --
DEBUG "End List"

################################################################################
# END
################################################################################
#
# $Copyright: 2015 The FrauBSD Project. All rights reserved. $
#
# $FrauBSD: .hooks/post-commit 2015-10-20 22:43:04 -0700 freebsdfrau $
#
################################################################################
