#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Hook to run after a successful `git commit' $
#
############################################################ INFORMATION
#
# System requirements: git(1) ls(1)
#
############################################################ MAIN

DEBUG(){ [ ! "$DEBUG" ] || echo "DEBUG: $*"; }
DEBUG "$0 $*"

# Do a simple `ls -l' of recently committed files
DEBUG "Listing committed files..."
git show --name-only -z --format= | xargs -r0 ls -l --
DEBUG "End List"

################################################################################
# END
################################################################################
#
# $Copyright: 2015 The FrauBSD Project. All rights reserved. $
#
# $FrauBSD: .hooks/post-commit 2015-11-14 21:56:06 -0800 freebsdfrau $
#
################################################################################
