#!/bin/sh
############################################################ IDENT(1)
#
# $Title: Hook to run before `git commit' $
#
############################################################ INFORMATION
#
# System requirements: git(1)
# See also: .filters/fraubsd-keywords
#
############################################################ MAIN

DEBUG(){ [ ! "$DEBUG" ] || echo "DEBUG: $*"; }
DEBUG "$0 $*"

# Set keywords in modified text-files prior to commit
DEBUG "Keyword modifications..."
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -r0 .filters/fraubsd-keywords --
DEBUG "End List"

# Update the staging files
git diff --cached --name-only -z --diff-filter=ACM |
	xargs -r0 git add -u -v --

################################################################################
# END
################################################################################
#
# $Copyright: 2015 The FrauBSD Project. All rights reserved. $
#
# $FrauBSD: .hooks/pre-commit 2015-11-14 21:56:06 -0800 freebsdfrau $
#
################################################################################
